# Generated by Django 3.0 on 2019-12-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Fecha de edición'),
        ),
    ]
