# Generated by Django 3.0 on 2019-12-20 03:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog', verbose_name='Imgenes'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(default=datetime.datetime(2019, 12, 20, 3, 7, 8, 36965, tzinfo=utc), verbose_name='Fecha de Publicacion'),
        ),
    ]
