# Generated by Django 3.0 on 2019-12-20 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191219_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='vategories',
            new_name='categories',
        ),
    ]
