# Generated by Django 3.0 on 2019-12-24 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191224_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='videofile',
        ),
    ]
